[package]
name = "{{}}"
version = "0.1.0"
authors = ["[your_name] <you_email>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scale = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive", "full"] }

liquid_core = { version = "0.1.0", git = "https://github.com/vita-dounai/liquid", branch = "dev", package = "liquid_core", default-features = false }
liquid_lang = { version = "0.1.0", git = "https://github.com/vita-dounai/liquid", branch = "dev", package = "liquid_lang", default-features = false }
liquid_primitives = { version = "0.1.0", git = "https://github.com/vita-dounai/liquid", branch = "dev", package = "liquid_primitives", default-features = false }
liquid_abi_codec = { version = "0.1.0", git = "https://github.com/vita-dounai/liquid", branch = "dev", package = "liquid_abi_codec", default-features = false }
liquid_abi_gen = { version = "0.1.0", git = "https://github.com/vita-dounai/liquid", branch = "dev", package = "liquid_abi_gen", default-features = false, optional = true }
liquid_ty_mapping = { version = "0.1.0", git = "https://github.com/vita-dounai/liquid", branch = "dev", package = "liquid_ty_mapping", default-features = false }
liquid_prelude = { version = "0.1.0",  git = "https://github.com/vita-dounai/liquid", branch = "dev", package = "liquid_prelude", default-features = false }

[lib]
name = "{{}}"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation.
    "rlib",
]

[features]
default = ["std"]
std = [
    "liquid_core/std",
    "liquid_primitives/std",
    "scale/std",
]
liquid-abi-gen = [
    "std",
    "liquid_abi_gen",
    "liquid_lang/liquid-abi-gen",
]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
overflow-checks = true

[workspace]
members = [
    ".liquid/abi_gen",
]
exclude = [
    ".liquid",
]
